apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: deepiri-bedd
spec:
  selector:
    matchLabels:
      app: deepiri-bedd
  endpoints:
    - port: admin
      path: /metrics
      interval: 30s
