apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: deepiri-flint
spec:
  selector:
    matchLabels:
      app: deepiri-flint
  endpoints:
    - port: admin
      path: /metrics
      interval: 30s
