apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flint.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flint
  template:
    metadata:
      labels:
        app: flint
    spec:
      containers:
        - name: flint
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["serve"]
          ports:
            - containerPort: {{ .Values.service.adminPort }}
              name: admin
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            - name: FLINT_CONSUMER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FLINT_ADMIN_PORT
              value: {{ .Values.service.adminPort | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
          readinessProbe:
            httpGet:
              path: /healthz
              port: admin
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
