apiVersion: v1
kind: Service
metadata:
  name: {{ include "flint.fullname" . }}
spec:
  selector:
    app: flint
  ports:
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
